import { Product } from './types/product'

export const products: Product[] = [
  {
    id: 'sticker-001',
    name: 'Custom Logo Stickers',
    description: 'High-quality vinyl stickers with your custom logo. Perfect for branding vehicles, laptops, and more.',
    price: 15.99,
    category: 'stickers',
    image: '/products/stickers-001.jpg',
    stock: 50,
    sku: 'STK-001',
  },
  {
    id: 'sticker-002',
    name: 'UV Resistant Outdoor Stickers',
    description: 'Weather-proof stickers designed to withstand sun, rain, and extreme conditions.',
    price: 19.99,
    category: 'stickers',
    image: '/products/stickers-002.jpg',
    stock: 40,
    sku: 'STK-002',
  },
  {
    id: 'sticker-003',
    name: 'Holographic Sticker Pack',
    description: 'Eye-catching holographic stickers with premium finish. Pack of 10 assorted designs.',
    price: 24.99,
    category: 'stickers',
    image: '/products/stickers-003.jpg',
    stock: 30,
    sku: 'STK-003',
  },
  {
    id: 'merch-001',
    name: 'Branded T-Shirt',
    description: 'Premium quality cotton t-shirt with full-color front and back print. Available in S-XXL.',
    price: 34.99,
    category: 'merchandise',
    image: '/products/tshirt-001.jpg',
    stock: 25,
    sku: 'MER-001',
  },
  {
    id: 'merch-002',
    name: 'Branded Hoodie',
    description: 'Comfortable fleece hoodie with embroidered logo. Perfect for winter promotion.',
    price: 54.99,
    category: 'merchandise',
    image: '/products/hoodie-001.jpg',
    stock: 20,
    sku: 'MER-002',
  },
  {
    id: 'merch-003',
    name: 'Custom Printed Mug',
    description: 'Ceramic mug with custom 360-degree wraparound print. Heat-resistant and dishwasher safe.',
    price: 12.99,
    category: 'merchandise',
    image: '/products/mug-001.jpg',
    stock: 60,
    sku: 'MER-003',
  },
  {
    id: 'print-001',
    name: 'A3 Large Format Print',
    description: 'High-resolution 720dpi A3 sized print on premium matte paper. Perfect for posters and signage.',
    price: 29.99,
    category: 'prints',
    image: '/products/print-a3.jpg',
    stock: 100,
    sku: 'PRT-001',
  },
  {
    id: 'print-002',
    name: 'Banner Print',
    description: 'Custom vinyl banner print. Various sizes available. Weather-resistant and durable.',
    price: 49.99,
    category: 'prints',
    image: '/products/banner-001.jpg',
    stock: 15,
    sku: 'PRT-002',
  },
  {
    id: 'print-003',
    name: 'Business Card Bundle',
    description: 'Professional business cards. Pack of 500 cards with full-color printing on premium cardstock.',
    price: 39.99,
    category: 'prints',
    image: '/products/business-cards.jpg',
    stock: 45,
    sku: 'PRT-003',
  },
]
